apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sun_spring_boot
  labels:
    run: sunyi_spring_boot
spec:
  replicas: 1 
  selector:
    matchLabels:
     run: sunyi_spring_boot
  template:
   metadata:
      labels:
        run: sunyi_spring_boot
   spec:
     hostNetwork: true
     containers:
     - name: sun_spring_boot
       image: phx.ocir.io/oardc/sunyi/sun_spring_boot:latest
       imagePullPolicy: Always
       ports:
       - name: sun_spring_boot
         containerPort: 8080
         protocol: TCP
